import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Michael Pfister" />

        {/*used in social media preview widgets*/}
        <meta property="og:title" content="Create Next App" />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:image" content="/favicon.ico" />
        <meta property="og:url" content="https://nextjs.org/" />

        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </>
}

export default MyApp
