name: E2E on Chrome

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
